name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ '{{' }} runner.os {{ '}}' }}-pip-${{ '{{' }} hashFiles('**/requirements.txt') {{ '}}' }}
        restore-keys: |
          ${{ '{{' }} runner.os {{ '}}' }}-pip-
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
    - name: Install pandoc 2.9
      run: |
        wget https://github.com/jgm/pandoc/releases/download/2.9.2.1/pandoc-2.9.2.1-1-amd64.deb
        sudo dpkg -i pandoc-2.9.2.1-1-amd64.deb
    - name: Run cookiecutter
      run: |
        cookiecutter --no-input https://github.com/bonartm/cookiecutter-present.git
    - name: Build slides
      run: |
        cd present
        make html
